const actionTypes = {
    GET_HOME: 'GET_HOME',
    GET_CUR_SONG_ID: 'GET_CUR_SONG_ID',
    LOADING: 'LOADING',
    SET_CUR_SONG_DATA: 'SET_CUR_SONG_DATA',
    SET_CUR_ALBUM_ID: 'SET_CUR_ALBUM_ID',
    SET_RECENT: 'SET_RECENT',
    CURRENT_WIDTH: 'CURRENT_WIDTH',

    //Music
    PLAY: 'PLAY',
    SET_ALBUM: 'SET_ALBUM',
    PLAYLIST: 'PLAYLIST',
    SEARCH: 'SEARCH',
    ZERO_SCROLL: 'ZERO_SCROLL',
};

export default actionTypes;
